language: python

os:
  - linux

python:
  - "3.6"

sudo: false

install:
  - pip install numpy
  - pip install tensorflow
  - pip install keras
  - pip install pytest
  - pip install pytest-cov

before_script:

script:
  - make test
